services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    environment:
      GIN_MODE: debug
      # - DB_HOST=db
      # - DB_USER=root
      # - DB_PASSWORD=password
      # - DB_NAME=todo_app
    command: /usr/local/bin/air -c ./.air.toml
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_app
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db_conf/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s

volumes:
  db_data:

networks:
  app-network:
    driver: bridge